# Generated by Django 4.2.1 on 2023-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='image_text',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
